DROP VIEW `book_view`;
DROP TABLE `borrowed_book`;
DROP TABLE `users`;
DROP TABLE `book_author`;
DROP TABLE `authors`;
DROP TABLE `book_genre`;
DROP TABLE `genres`;
DROP TABLE `books`;
DROP TABLE `publishers`;